### ISSUE TITLE
partials not working?

### ISSUE THREAD

**Issue by levynir** [widmogrod/zf2-mustache-module#5]
Hey, thanks for making this code public.
A quick question, I cannot get partials to work. if I try to include a mustache partial it does not do anything (does not include the partial and does not give any error)
<pre><code>
index.mustache:
BOX {{>box}} BOX

box.mustache (in the same folder)
this is a box

output html:
BOX  BOX
</code></pre>

Am I doing something wrong?

**Comment by diego3** [comment]
i have fixed this ... i gonna make the pull request as soon as i can

**Comment by widmogrod** [comment]
Fantastic

**Comment by diego3** [comment]
Hi @widmogrod  , i make the pull request, you did see ?

**Comment by widmogrod** [comment]
There is no open pull request.

**Comment by diego3** [comment]
Oh... it is my first pull request.. something wrong was happened... :/ let me see here and latter i make it again

**Comment by widmogrod** [comment]
Merged. Thank you!
